In [11]:
## Import the dependencies.
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

In [12]:
# Store the CSV you saved created in part one into a DataFrame.
city_weather_df = pd.read_csv("data/WeatherPy_challenge.csv")
city_weather_df.rename(columns={"Rain Inches (last 3hours)":"RainInches", "Snow Inches (last 3hours)":"SnowInches"}, inplace=True)
city_weather_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,RainInches,SnowInches
0,0,Lebyazhye,RU,2020-01-04 06:08:31,59.96,29.42,35.01,86,20,17.90,few clouds,0.0,0.0
1,1,Upernavik,GL,2020-01-04 06:08:14,72.79,-56.15,-18.78,98,100,16.93,light snow,0.0,0.5
2,2,Cherskiy,RU,2020-01-04 06:08:32,68.75,161.30,0.12,62,10,9.73,clear sky,0.0,0.0
3,3,Albany,US,2020-01-04 06:04:10,42.65,-73.75,41.00,86,90,1.34,overcast clouds,0.0,0.0
4,4,Atuona,PF,2020-01-04 06:08:33,-9.80,-139.03,80.69,74,4,16.20,clear sky,0.0,0.0

In [13]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [14]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
raining = input("Do you want it to be raining? (yes/no) ")
snowing = input ("Do you want it to be snowing? (yes/no) ")

What is the minimum temperature you would like for your trip? 35
What is the maximum temperature you would like for your trip? 100
Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [15]:
preferred_cities_df = city_weather_df.loc[(city_weather_df["Max Temp"] <= max_temp) & (city_weather_df["Max Temp"] >= min_temp)]
if (raining == "yes"):
    preferred_cities_df = preferred_cities_df.loc[(preferred_cities_df["RainInches"] > 0)]
elif (snowing == "yes"):
    preferred_cities_df = preferred_cities_df.loc[(preferred_cities_df["SnowInches"] > 0)] 
    
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,RainInches,SnowInches
0,0,Lebyazhye,RU,2020-01-04 06:08:31,59.96,29.42,35.01,86,20,17.90,few clouds,0.00,0.0
3,3,Albany,US,2020-01-04 06:04:10,42.65,-73.75,41.00,86,90,1.34,overcast clouds,0.00,0.0
4,4,Atuona,PF,2020-01-04 06:08:33,-9.80,-139.03,80.69,74,4,16.20,clear sky,0.00,0.0
5,5,Sambava,MG,2020-01-04 06:08:33,-14.27,50.17,87.55,61,56,0.67,broken clouds,0.00,0.0
6,6,Lebu,ET,2020-01-04 06:08:34,8.96,38.73,57.20,62,20,6.93,few clouds,0.00,0.0
7,7,Carutapera,BR,2020-01-04 06:08:34,-1.20,-46.02,81.00,78,40,8.19,moderate rain,3.38,0.0
9,9,Bredasdorp,ZA,2020-01-04 06:08:36,-34.53,20.04,72.00,68,4,5.82,clear sky,0.00,0.0
10,10,Butaritari,KI,2020-01-04 06:08:37,3.07,172.79,83.59,77,100,12.30,light rain,1.87,0.0
11,11,Saint-Philippe,CA,2020-01-04 06:08:38,45.36,-73.48,39.20,100,90,3.87,overcast clouds,0.00,0.0
12,12,Katete,UG,2020-01-04 06:08:39,-0.78,29.75,67.19,69,96,1.63,overcast clouds,0.00,0.0

In [16]:
preferred_cities_df.count()

City_ID                402
City                   402
Country                398
Date                   402
Lat                    402
Lng                    402
Max Temp               402
Humidity               402
Cloudiness             402
Wind Speed             402
Current Description    402
RainInches             402
SnowInches             402
dtype: int64

In [17]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp",  "Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Lebyazhye,RU,35.01,few clouds,59.96,29.42,
3,Albany,US,41.00,overcast clouds,42.65,-73.75,
4,Atuona,PF,80.69,clear sky,-9.80,-139.03,
5,Sambava,MG,87.55,broken clouds,-14.27,50.17,
6,Lebu,ET,57.20,few clouds,8.96,38.73,
7,Carutapera,BR,81.00,moderate rain,-1.20,-46.02,
9,Bredasdorp,ZA,72.00,clear sky,-34.53,20.04,
10,Butaritari,KI,83.59,light rain,3.07,172.79,
11,Saint-Philippe,CA,39.20,overcast clouds,45.36,-73.48,
12,Katete,UG,67.19,overcast clouds,-0.78,29.75,

In [18]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
     # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [19]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Lebyazhye,RU,35.01,few clouds,59.96,29.42,Dom Kovrov
3,Albany,US,41.00,overcast clouds,42.65,-73.75,Hilton Albany
4,Atuona,PF,80.69,clear sky,-9.80,-139.03,Villa Enata
5,Sambava,MG,87.55,broken clouds,-14.27,50.17,Melrose
6,Lebu,ET,57.20,few clouds,8.96,38.73,Dah-Lak Guest House
7,Carutapera,BR,81.00,moderate rain,-1.20,-46.02,Lidera
9,Bredasdorp,ZA,72.00,clear sky,-34.53,20.04,Bredasdorp Country Manor
10,Butaritari,KI,83.59,light rain,3.07,172.79,Isles Sunset Lodge
11,Saint-Philippe,CA,39.20,overcast clouds,45.36,-73.48,Camping St-Andre
12,Katete,UG,67.19,overcast clouds,-0.78,29.75,

In [20]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

In [21]:
# %%
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [22]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

#embed_minimal_html('export.html', views=[fig])

# Save the figure.
#fig.save("weather_data/Hotels.png")

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
## Upload the CSV file as part of your submission as WeatherPy_challenge.csv.

# Create the output file (CSV).
output_data_file = "data/WeatherPy_vacation.csv"

# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")